// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace KojackGames.Blackjack.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Dealer Rules")]
    public partial class DealerRulesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "006-DealerPlayingRules.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Dealer Rules", "In order to give a player a sporting chance\r\nAs a dealer\r\nI will hit on any score" +
                    " below 17 and stand on any score of 17 and above", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dealer plays until he gets over 17")]
        public virtual void DealerPlaysUntilHeGetsOver17()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dealer plays until he gets over 17", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 7
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table1);
#line 10
 testRunner.And("I have started a new game and bet \"5\"");
#line 11
 testRunner.And("the dealers has dealt me in");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table2.AddRow(new string[] {
                        "Clubs",
                        "Jack"});
#line 12
 testRunner.And("my hand contains the following cards:", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table3.AddRow(new string[] {
                        "Spades",
                        "Five"});
            table3.AddRow(new string[] {
                        "Hearts",
                        "Six"});
#line 16
 testRunner.And("the dealers hand contains the following cards:", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Two"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Four"});
            table4.AddRow(new string[] {
                        "Clubs",
                        "Two"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Seven"});
#line 20
 testRunner.And("the deck contains the following cards:", ((string)(null)), table4);
#line 26
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 27
 testRunner.When("I stick");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table5.AddRow(new string[] {
                        "Five of Spades"});
            table5.AddRow(new string[] {
                        "Six of Hearts"});
            table5.AddRow(new string[] {
                        "Two of Diamonds"});
            table5.AddRow(new string[] {
                        "Four of Diamonds"});
#line 28
 testRunner.Then("the dealers hand should show the following cards:", ((string)(null)), table5);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
