// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace KojackGames.Blackjack.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Split")]
    public partial class SplitFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "008-Split.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Split", "In order to increase my chance of winning\r\nAs a player\r\nI should be offered to sp" +
                    "lit my hand if initial two cards make a pair", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Offer to split")]
        public virtual void OfferToSplit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Offer to split", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 7
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table1);
#line 10
 testRunner.And("I have started a new game and bet \"5\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table2.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table2.AddRow(new string[] {
                        "Clubs",
                        "Eight"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Three"});
#line 11
 testRunner.And("the deck contains the following cards:", ((string)(null)), table2);
#line 17
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 18
 testRunner.When("I click on the deal button");
#line 19
 testRunner.Then("I should be offered to split my hand");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Trying to split without enough money")]
        public virtual void TryingToSplitWithoutEnoughMoney()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Trying to split without enough money", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table3.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 22
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table3);
#line 25
 testRunner.And("I have started a new game and bet \"10\"");
#line 26
 testRunner.And("I have \"1\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table4.AddRow(new string[] {
                        "Clubs",
                        "Eight"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Three"});
#line 27
 testRunner.And("the deck contains the following cards:", ((string)(null)), table4);
#line 33
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 34
 testRunner.When("I click on the deal button");
#line 35
 testRunner.When("I click on the split button");
#line 36
 testRunner.Then("I should be asked \"Please cash in to Split. You need at least $10.00 dollars.\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Split hand")]
        public virtual void SplitHand()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Split hand", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table5.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 39
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table5);
#line 42
 testRunner.And("I have started a new game and bet \"5\"");
#line 43
 testRunner.And("I have \"30\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table6.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table6.AddRow(new string[] {
                        "Clubs",
                        "Eight"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Three"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Four"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Seven"});
#line 44
 testRunner.And("the deck contains the following cards:", ((string)(null)), table6);
#line 52
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 53
 testRunner.When("I click on the deal button");
#line 54
 testRunner.Then("I should be offered to split my hand");
#line 55
 testRunner.When("I click on the split button");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table7.AddRow(new string[] {
                        "Eight of Diamonds"});
            table7.AddRow(new string[] {
                        "Four of Hearts"});
#line 56
 testRunner.Then("hand \"A\" should show the following cards:", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table8.AddRow(new string[] {
                        "Eight of Clubs"});
            table8.AddRow(new string[] {
                        "Seven of Hearts"});
#line 60
 testRunner.And("hand \"B\" should show the following cards:", ((string)(null)), table8);
#line 64
 testRunner.And("my pot should show \"$25.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Split hand and complete game")]
        public virtual void SplitHandAndCompleteGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Split hand and complete game", ((string[])(null)));
#line 67
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table9.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 68
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table9);
#line 71
 testRunner.And("I have started a new game and bet \"5\"");
#line 72
 testRunner.And("I have \"30\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table10.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table10.AddRow(new string[] {
                        "Clubs",
                        "Eight"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Three"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Four"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Seven"});
            table10.AddRow(new string[] {
                        "Clubs",
                        "Four"});
            table10.AddRow(new string[] {
                        "Spades",
                        "Four"});
            table10.AddRow(new string[] {
                        "Spades",
                        "Jack"});
            table10.AddRow(new string[] {
                        "Spades",
                        "Queen"});
            table10.AddRow(new string[] {
                        "Clubs",
                        "Queen"});
#line 73
 testRunner.And("the deck contains the following cards:", ((string)(null)), table10);
#line 86
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 87
 testRunner.When("I click on the deal button");
#line 88
 testRunner.Then("I should be offered to split my hand");
#line 89
 testRunner.When("I click on the split button");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table11.AddRow(new string[] {
                        "Eight of Diamonds"});
            table11.AddRow(new string[] {
                        "Four of Hearts"});
#line 90
 testRunner.Then("hand \"A\" should show the following cards:", ((string)(null)), table11);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table12.AddRow(new string[] {
                        "Eight of Clubs"});
            table12.AddRow(new string[] {
                        "Seven of Hearts"});
#line 94
 testRunner.And("hand \"B\" should show the following cards:", ((string)(null)), table12);
#line 98
 testRunner.When("I hit");
#line 99
 testRunner.When("I stick");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table13.AddRow(new string[] {
                        "Eight of Diamonds"});
            table13.AddRow(new string[] {
                        "Four of Hearts"});
            table13.AddRow(new string[] {
                        "Four of Clubs"});
#line 100
 testRunner.Then("hand \"A\" should show the following cards:", ((string)(null)), table13);
#line 105
 testRunner.When("I hit");
#line 106
 testRunner.When("I stick");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table14.AddRow(new string[] {
                        "Eight of Clubs"});
            table14.AddRow(new string[] {
                        "Seven of Hearts"});
            table14.AddRow(new string[] {
                        "Four of Spades"});
#line 107
 testRunner.Then("hand \"B\" should show the following cards:", ((string)(null)), table14);
#line 112
 testRunner.Then("players hand \"A\" should have won");
#line 113
 testRunner.Then("players hand \"B\" should have won");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
