// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace KojackGames.Blackjack.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Hit")]
    public partial class HitFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "003-HitHand.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Hit", "In order to achieve 21\r\nAs a player\r\nI should be able to Hit and receive an extra" +
                    " card from the pack", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Option to Hit")]
        public virtual void OptionToHit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Option to Hit", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 7
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table1);
#line 10
 testRunner.And("I have started a new game and bet \"5\"");
#line 11
 testRunner.And("the dealers has dealt me in");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table2.AddRow(new string[] {
                        "Clubs",
                        "Six"});
#line 12
 testRunner.And("my hand contains the following cards:", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table3.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table3.AddRow(new string[] {
                        "Hearts",
                        "Three"});
#line 16
 testRunner.And("the dealers hand contains the following cards:", ((string)(null)), table3);
#line 20
    testRunner.When("I navigate to the game play screen");
#line 21
 testRunner.Then("I should given the option to hit");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Hit")]
        public virtual void Hit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Hit", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table4.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 24
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table4);
#line 27
 testRunner.And("I have started a new game and bet \"5\"");
#line 28
 testRunner.And("the dealers has dealt me in");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table5.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table5.AddRow(new string[] {
                        "Clubs",
                        "Six"});
#line 29
 testRunner.And("my hand contains the following cards:", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Three"});
#line 33
 testRunner.And("the dealers hand contains the following cards:", ((string)(null)), table6);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table7.AddRow(new string[] {
                        "Hearts",
                        "Four"});
            table7.AddRow(new string[] {
                        "Hearts",
                        "Five"});
#line 37
 testRunner.And("the deck contains the following cards:", ((string)(null)), table7);
#line 41
 testRunner.And("I have navigated to the game play screen");
#line 42
 testRunner.When("I hit");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "card"});
            table8.AddRow(new string[] {
                        "Two of Hearts"});
            table8.AddRow(new string[] {
                        "Six of Clubs"});
            table8.AddRow(new string[] {
                        "Four of Hearts"});
#line 43
 testRunner.Then("my hand should show the following cards:", ((string)(null)), table8);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
