// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace KojackGames.Blackjack.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Win game")]
    public partial class WinGameFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "005-WinGame.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Win game", "In order to win a hand of Blackjack\r\nAs a player\r\nI must be closer to 21 than the" +
                    " dealer and not go bust", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player Gets blackjack with two cards")]
        public virtual void PlayerGetsBlackjackWithTwoCards()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player Gets blackjack with two cards", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 7
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table1);
#line 10
 testRunner.And("I have started a new game and bet \"5\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table2.AddRow(new string[] {
                        "Diamonds",
                        "Ace"});
            table2.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table2.AddRow(new string[] {
                        "Clubs",
                        "Ten"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Two"});
#line 11
 testRunner.And("the deck contains the following cards:", ((string)(null)), table2);
#line 17
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 18
 testRunner.When("I click on the deal button");
#line 19
 testRunner.Then("the player should win the game");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Dealer Gets blackjack with two cards")]
        public virtual void DealerGetsBlackjackWithTwoCards()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dealer Gets blackjack with two cards", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table3.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 22
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table3);
#line 25
 testRunner.And("I have started a new game and bet \"5\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Ace"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table4.AddRow(new string[] {
                        "Clubs",
                        "Ten"});
#line 26
 testRunner.And("the deck contains the following cards:", ((string)(null)), table4);
#line 32
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 33
 testRunner.When("I click on the deal button");
#line 34
 testRunner.When("I stick");
#line 35
 testRunner.Then("the player should lose the game");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Both player and dealer get blackjack so game ends in draw")]
        public virtual void BothPlayerAndDealerGetBlackjackSoGameEndsInDraw()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Both player and dealer get blackjack so game ends in draw", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table5.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 38
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table5);
#line 41
 testRunner.And("I have started a new game and bet \"5\"");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
            table6.AddRow(new string[] {
                        "Spades",
                        "Ten"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table6.AddRow(new string[] {
                        "Clubs",
                        "Ace"});
#line 42
 testRunner.And("the deck contains the following cards:", ((string)(null)), table6);
#line 48
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 49
 testRunner.When("I click on the deal button");
#line 50
 testRunner.Then("the game should be drawn");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player sticks at 20 and dealer sticks at 19 so players wins")]
        public virtual void PlayerSticksAt20AndDealerSticksAt19SoPlayersWins()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player sticks at 20 and dealer sticks at 19 so players wins", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table7.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 53
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table7);
#line 56
 testRunner.And("I have started a new game and bet \"5\"");
#line 57
 testRunner.And("the dealers has dealt me in");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table8.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table8.AddRow(new string[] {
                        "Clubs",
                        "King"});
#line 58
 testRunner.And("my hand contains the following cards:", ((string)(null)), table8);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table9.AddRow(new string[] {
                        "Spades",
                        "Ten"});
            table9.AddRow(new string[] {
                        "Hearts",
                        "Six"});
#line 62
 testRunner.And("the dealers hand contains the following cards:", ((string)(null)), table9);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table10.AddRow(new string[] {
                        "Diamonds",
                        "Three"});
#line 66
 testRunner.And("the deck contains the following cards:", ((string)(null)), table10);
#line 69
    testRunner.And("I have navigated to the game play screen to play a hand");
#line 70
 testRunner.When("I stick");
#line 71
 testRunner.Then("the player should win the game");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player sticks at 16 and dealer sticks at 19 so players wins")]
        public virtual void PlayerSticksAt16AndDealerSticksAt19SoPlayersWins()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player sticks at 16 and dealer sticks at 19 so players wins", ((string[])(null)));
#line 73
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table11.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 74
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table11);
#line 77
 testRunner.And("I have started a new game and bet \"5\"");
#line 78
 testRunner.And("the dealers has dealt me in");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table12.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table12.AddRow(new string[] {
                        "Clubs",
                        "Six"});
#line 79
 testRunner.And("my hand contains the following cards:", ((string)(null)), table12);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table13.AddRow(new string[] {
                        "Spades",
                        "Ten"});
            table13.AddRow(new string[] {
                        "Hearts",
                        "Five"});
#line 83
 testRunner.And("the dealers hand contains the following cards:", ((string)(null)), table13);
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table14.AddRow(new string[] {
                        "Diamonds",
                        "Four"});
#line 87
 testRunner.And("the deck contains the following cards:", ((string)(null)), table14);
#line 90
    testRunner.And("I have navigated to the game play screen to play a hand");
#line 91
 testRunner.When("I stick");
#line 92
 testRunner.Then("the player should lose the game");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Player sticks and dealer busts so player wins")]
        public virtual void PlayerSticksAndDealerBustsSoPlayerWins()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Player sticks and dealer busts so player wins", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table15.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 95
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table15);
#line 98
 testRunner.And("I have started a new game and bet \"5\"");
#line 99
 testRunner.And("the dealers has dealt me in");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table16.AddRow(new string[] {
                        "Hearts",
                        "Ten"});
            table16.AddRow(new string[] {
                        "Clubs",
                        "Jack"});
#line 100
 testRunner.And("my hand contains the following cards:", ((string)(null)), table16);
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table17.AddRow(new string[] {
                        "Spades",
                        "Ten"});
            table17.AddRow(new string[] {
                        "Hearts",
                        "Six"});
#line 104
 testRunner.And("the dealers hand contains the following cards:", ((string)(null)), table17);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table18.AddRow(new string[] {
                        "Diamonds",
                        "Ten"});
#line 108
 testRunner.And("the deck contains the following cards:", ((string)(null)), table18);
#line 111
    testRunner.And("I have navigated to the game play screen to play a hand");
#line 112
 testRunner.When("I stick");
#line 113
 testRunner.Then("the player should win the game");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
