// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.225
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace KojackGames.Blackjack.Acceptance.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Insurance")]
    public partial class InsuranceFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "009-Insurance.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Insurance", "In order to increases my chances of making money\r\nAs a player\r\nI should be offere" +
                    "d an insurance bet", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Offer insurance bet")]
        public virtual void OfferInsuranceBet()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Offer insurance bet", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 7
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table1);
#line 10
 testRunner.And("I have started a new game and bet \"10\"");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table2.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table2.AddRow(new string[] {
                        "Hearts",
                        "Three"});
#line 11
 testRunner.And("the deck contains the following cards:", ((string)(null)), table2);
#line 17
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 18
 testRunner.When("I click on the deal button");
#line 19
 testRunner.Then("I should be given the option for insurance");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Offer insurance bet only on visible ace")]
        public virtual void OfferInsuranceBetOnlyOnVisibleAce()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Offer insurance bet only on visible ace", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table3.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 22
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table3);
#line 25
 testRunner.And("I have started a new game and bet \"10\"");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table4.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Three"});
            table4.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
#line 26
 testRunner.And("the deck contains the following cards:", ((string)(null)), table4);
#line 32
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 33
 testRunner.When("I click on the deal button");
#line 34
 testRunner.Then("I should not be given the option for insurance");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Take offer of insurance")]
        public virtual void TakeOfferOfInsurance()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Take offer of insurance", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table5.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 37
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table5);
#line 40
 testRunner.And("I have started a new game and bet \"10\"");
#line 41
 testRunner.And("I have \"100\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table6.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table6.AddRow(new string[] {
                        "Hearts",
                        "Three"});
#line 42
 testRunner.And("the deck contains the following cards:", ((string)(null)), table6);
#line 48
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 49
 testRunner.When("I click on the deal button");
#line 50
 testRunner.Then("I should be given the option for insurance");
#line 51
 testRunner.When("I click on take insurance");
#line 52
 testRunner.Then("my pot should show \"$95.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Take offer of insurance with dealer not getting blackjack and player losing")]
        public virtual void TakeOfferOfInsuranceWithDealerNotGettingBlackjackAndPlayerLosing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Take offer of insurance with dealer not getting blackjack and player losing", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table7.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 55
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table7);
#line 58
 testRunner.And("I have started a new game and bet \"10\"");
#line 59
 testRunner.And("I have \"100\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table8.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table8.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
            table8.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table8.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table8.AddRow(new string[] {
                        "Hearts",
                        "Seven"});
#line 60
 testRunner.And("the deck contains the following cards:", ((string)(null)), table8);
#line 67
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 68
 testRunner.When("I click on the deal button");
#line 69
 testRunner.When("I click on take insurance");
#line 70
 testRunner.Then("my pot should show \"$95.00\" dollars");
#line 71
 testRunner.When("I stick");
#line 72
 testRunner.Then("my pot should show \"$95.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Take offer of insurance with dealer getting blackjack and player losing")]
        public virtual void TakeOfferOfInsuranceWithDealerGettingBlackjackAndPlayerLosing()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Take offer of insurance with dealer getting blackjack and player losing", ((string[])(null)));
#line 74
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name",
                        "Password"});
            table9.AddRow(new string[] {
                        "Scott@elbandit.co.uk",
                        "Scott",
                        "Cheese@123"});
#line 75
 testRunner.Given("that I have logged in with an account with the following details", ((string)(null)), table9);
#line 78
 testRunner.And("I have started a new game and bet \"10\"");
#line 79
 testRunner.And("I have \"100\" dollars in my pot");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Suit",
                        "Value"});
            table10.AddRow(new string[] {
                        "Diamonds",
                        "Eight"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Ace"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Two"});
            table10.AddRow(new string[] {
                        "Hearts",
                        "Jack"});
#line 80
 testRunner.And("the deck contains the following cards:", ((string)(null)), table10);
#line 86
 testRunner.And("I have navigated to the game play screen to play a hand");
#line 87
 testRunner.When("I click on the deal button");
#line 88
 testRunner.When("I click on take insurance");
#line 89
 testRunner.Then("my pot should show \"$95.00\" dollars");
#line 90
 testRunner.When("I stick");
#line 91
 testRunner.Then("my pot should show \"$110.00\" dollars");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
